export const questionBank = {
  questions: [
    { station: "Marina Bay", abbr: "MRB" },
    { station: "Bayfront", abbr: "BFT" },
    { station: "Dhoby Ghaut", abbr: "DBG" },
    { station: "Bras Basah", abbr: "BBS" },
    { station: "Esplanade", abbr: "EPN" },
    { station: "Promenade", abbr: "PMN" },
    { station: "Nicoll Highway", abbr: "NCH" },
    { station: "Stadium", abbr: "SDM" },
    { station: "Mountbatten", abbr: "MBT" },
    { station: "Dakota", abbr: "DKT" },
    { station: "Paya Lebar", abbr: "PYL" },
    { station: "MacPherson", abbr: "MPS" },
    { station: "Tai Seng", abbr: "TSG" },
    { station: "Bartley", abbr: "BLY" },
    { station: "Serangoon", abbr: "SER" },
    { station: "Lorong Chuan", abbr: "LRC" },
    { station: "Bishan", abbr: "BSH" },
    { station: "Marymount", abbr: "MRM" },
    { station: "Caldecott", abbr: "CDT" },
    { station: "Botanic Gardens", abbr: "BTN" },
    { station: "Farrer Road", abbr: "FRR" },
    { station: "Holland Village", abbr: "HLV" },
    { station: "Buona Vista", abbr: "BNV" },
    { station: "one-north", abbr: "ONH" },
    { station: "Kent Ridge", abbr: "KRG" },
    { station: "Haw Par Villa", abbr: "HPV" },
    { station: "Pasir Panjang", abbr: "PPJ" },
    { station: "Labrador Park", abbr: "LBD" },
    { station: "Telok Blangah", abbr: "TLB" },
    { station: "HarbourFront", abbr: "HBF" },
  ],
};
