export const questionBank = {
  questions: [
    { station: "Bukit Panjang", abbr: "BKP" },
    { station: "Cashew", abbr: "CSW" },
    { station: "Hillview", abbr: "HVW" },
    { station: "Beauty World", abbr: "BTW" },
    { station: "King Albert Park", abbr: "KAP" },
    { station: "Sixth Avenue", abbr: "SAV" },
    { station: "Tan Kah Kee", abbr: "TKK" },
    { station: "Botanic Gardens", abbr: "BTN" },
    { station: "Stevens", abbr: "STV" },
    { station: "Newton", abbr: "NEW" },
    { station: "Little India", abbr: "LTI" },
    { station: "Rochor", abbr: "RCR" },
    { station: "Bugis", abbr: "BGS" },
    { station: "Promenade", abbr: "PMN" },
    { station: "Bayfront", abbr: "BFT" },
    { station: "Downtown", abbr: "DTN" },
    { station: "Telok Ayer", abbr: "TLA" },
    { station: "Chinatown", abbr: "CNT" },
    { station: "Fort Canning", abbr: "FCN" },
    { station: "Bencoolen", abbr: "BCL" },
    { station: "Jalan Besar", abbr: "JLB" },
    { station: "Bendemeer", abbr: "BDM" },
    { station: "Geylang Bahru", abbr: "GLB" },
    { station: "Mattar", abbr: "MTR" },
    { station: "MacPherson", abbr: "MPS" },
    { station: "Ubi", abbr: "UBI" },
    { station: "Kaki Bukit", abbr: "KKB" },
    { station: "Bedok North", abbr: "BDN" },
    { station: "Bedok Reservoir", abbr: "BDR" },
    { station: "Tampines West", abbr: "TPW" },
    { station: "Tampines", abbr: "TAM" },
    { station: "Tampines East", abbr: "TPE" },
    { station: "Expo", abbr: "XPO" },
    { station: "Upper Changi", abbr: "UPC" },
  ],
};
