export const questionBank = {
  questions: [
    { station: "HarbourFront", abbr: "HBF" },
    { station: "Outram Park", abbr: "OTP" },
    { station: "Chinatown", abbr: "CNT" },
    { station: "Clarke Quay", abbr: "CQY" },
    { station: "Dhoby Ghaut", abbr: "DBG" },
    { station: "Little India", abbr: "LTI" },
    { station: "Farrer Park", abbr: "FRP" },
    { station: "Boon Keng", abbr: "BNK" },
    { station: "Potong Pasir", abbr: "PTP" },
    { station: "Woodleigh", abbr: "WLH" },
    { station: "Serangoon", abbr: "SER" },
    { station: "Kovan", abbr: "KVN" },
    { station: "Hougang", abbr: "HGN" },
    { station: "Buangkok", abbr: "BGK" },
    { station: "Sengkang", abbr: "SKG" },
    { station: "Punggol", abbr: "PGL" },
  ],
};
