export const questionBank = {
  questions: [
    { station: "Jurong East", abbr: "JUR" },
    { station: "Bukit Batok", abbr: "BBT" },
    { station: "Bukit Gombak", abbr: "BGB" },
    { station: "Choa Chu Kang", abbr: "CCK" },
    { station: "Yew Tee", abbr: "YWT" },
    { station: "Kranji", abbr: "KRJ" },
    { station: "Marsiling", abbr: "MSL" },
    { station: "Woodlands", abbr: "WDL" },
    { station: "Admiralty", abbr: "ADM" },
    { station: "Sembawang", abbr: "SBW" },
    { station: "Canberra", abbr: "CBR" },
    { station: "Yishun", abbr: "YIS" },
    { station: "Khatib", abbr: "KTB" },
    { station: "Yio Chu Kang", abbr: "YCK" },
    { station: "Ang Mo Kio", abbr: "AMK" },
    { station: "Bishan", abbr: "BSH" },
    { station: "Braddell", abbr: "BDL" },
    { station: "Toa Payoh", abbr: "TAP" },
    { station: "Novena", abbr: "NOV" },
    { station: "Newton", abbr: "NEW" },
    { station: "Orchard", abbr: "ORC" },
    { station: "Somerset", abbr: "SOM" },
    { station: "Dhoby Ghaut", abbr: "DBG" },
    { station: "City Hall", abbr: "CTH" },
    { station: "Raffles Place", abbr: "RFP" },
    { station: "Marina Bay", abbr: "MRB" },
    { station: "Marina South Pier", abbr: "MSP" },
  ],
};
