export const questionBank = {
  questions: [
    { station: "Jurong East", abbr: "JUR" },
    { station: "Bukit Batok", abbr: "BBT" },
    { station: "Bukit Gombak", abbr: "BGB" },
    { station: "Choa Chu Kang", abbr: "CCK" },
    { station: "Yew Tee", abbr: "YWT" },
    { station: "Kranji", abbr: "KRJ" },
    { station: "Marsiling", abbr: "MSL" },
    { station: "Woodlands", abbr: "WDL" },
    { station: "Admiralty", abbr: "ADM" },
    { station: "Sembawang", abbr: "SBW" },
    { station: "Canberra", abbr: "CBR" },
    { station: "Yishun", abbr: "YIS" },
    { station: "Khatib", abbr: "KTB" },
    { station: "Yio Chu Kang", abbr: "YCK" },
    { station: "Ang Mo Kio", abbr: "AMK" },
    { station: "Bishan", abbr: "BSH" },
    { station: "Braddell", abbr: "BDL" },
    { station: "Toa Payoh", abbr: "TAP" },
    { station: "Novena", abbr: "NOV" },
    { station: "Newton", abbr: "NEW" },
    { station: "Orchard", abbr: "ORC" },
    { station: "Somerset", abbr: "SOM" },
    { station: "Dhoby Ghaut", abbr: "DBG" },
    { station: "City Hall", abbr: "CTH" },
    { station: "Raffles Place", abbr: "RFP" },
    { station: "Marina Bay", abbr: "MRB" },
    { station: "Marina South Pier", abbr: "MSP" },
    { station: "Pasir Ris", abbr: "PSR" },
    { station: "Tampines", abbr: "TAM" },
    { station: "Simei", abbr: "SIM" },
    { station: "Tanah Merah", abbr: "TNM" },
    { station: "Bedok", abbr: "BDK" },
    { station: "Kembangan", abbr: "KEM" },
    { station: "Eunos", abbr: "EUN" },
    { station: "Paya Lebar", abbr: "PYL" },
    { station: "Aljunied", abbr: "ALJ" },
    { station: "Kallang", abbr: "KAL" },
    { station: "Lavender", abbr: "LVR" },
    { station: "Bugis", abbr: "BGS" },
    { station: "Tanjong Pagar", abbr: "TPG" },
    { station: "Outram Park", abbr: "OTP" },
    { station: "Tiong Bahru", abbr: "TIB" },
    { station: "Redhill", abbr: "RDH" },
    { station: "Queenstown", abbr: "QUE" },
    { station: "Commonwealth", abbr: "COM" },
    { station: "Buona Vista", abbr: "BNV" },
    { station: "Dover", abbr: "DVR" },
    { station: "Clementi", abbr: "CLE" },
    { station: "Chinese Garden", abbr: "CNG" },
    { station: "Lakeside", abbr: "LKS" },
    { station: "Boon Lay", abbr: "BNL" },
    { station: "Pioneer", abbr: "PNR" },
    { station: "Joo Koon", abbr: "JKN" },
    { station: "Gul Circle", abbr: "GCL" },
    { station: "Tuas Crescent", abbr: "TCR" },
    { station: "Tuas West Road", abbr: "TWR" },
    { station: "Tuas Link", abbr: "TLK" },
    { station: "Expo", abbr: "XPO" },
    { station: "Changi Airport", abbr: "CGA" },
    { station: "HarbourFront", abbr: "HBF" },
    { station: "Chinatown", abbr: "CNT" },
    { station: "Clarke Quay", abbr: "CQY" },
    { station: "Little India", abbr: "LTI" },
    { station: "Farrer Park", abbr: "FRP" },
    { station: "Boon Keng", abbr: "BNK" },
    { station: "Potong Pasir", abbr: "PTP" },
    { station: "Woodleigh", abbr: "WLH" },
    { station: "Serangoon", abbr: "SER" },
    { station: "Kovan", abbr: "KVN" },
    { station: "Hougang", abbr: "HGN" },
    { station: "Buangkok", abbr: "BGK" },
    { station: "Sengkang", abbr: "SKG" },
    { station: "Punggol", abbr: "PGL" },
    { station: "Bras Basah", abbr: "BBS" },
    { station: "Esplanade", abbr: "EPN" },
    { station: "Promenade", abbr: "PMN" },
    { station: "Nicoll Highway", abbr: "NCH" },
    { station: "Stadium", abbr: "SDM" },
    { station: "Mountbatten", abbr: "MBT" },
    { station: "Dakota", abbr: "DKT" },
    { station: "MacPherson", abbr: "MPS" },
    { station: "Tai Seng", abbr: "TSG" },
    { station: "Bartley", abbr: "BLY" },
    { station: "Lorong Chuan", abbr: "LRC" },
    { station: "Marymount", abbr: "MRM" },
    { station: "Caldecott", abbr: "CDT" },
    { station: "Botanic Gardens", abbr: "BTN" },
    { station: "Farrer Road", abbr: "FRR" },
    { station: "Holland Village", abbr: "HLV" },
    { station: "one-north", abbr: "ONH" },
    { station: "Kent Ridge", abbr: "KRG" },
    { station: "Haw Par Villa", abbr: "HPV" },
    { station: "Pasir Panjang", abbr: "PPJ" },
    { station: "Labrador Park", abbr: "LBD" },
    { station: "Telok Blangah", abbr: "TLB" },
    { station: "Bayfront", abbr: "BFT" },
    { station: "Bukit Panjang", abbr: "BKP" },
    { station: "Cashew", abbr: "CSW" },
    { station: "Hillview", abbr: "HVW" },
    { station: "Beauty World", abbr: "BTW" },
    { station: "King Albert Park", abbr: "KAP" },
    { station: "Sixth Avenue", abbr: "SAV" },
    { station: "Tan Kah Kee", abbr: "TKK" },
    { station: "Stevens", abbr: "STV" },
    { station: "Rochor", abbr: "RCR" },
    { station: "Downtown", abbr: "DTN" },
    { station: "Telok Ayer", abbr: "TLA" },
    { station: "Fort Canning", abbr: "FCN" },
    { station: "Bencoolen", abbr: "BCL" },
    { station: "Jalan Besar", abbr: "JLB" },
    { station: "Bendemeer", abbr: "BDM" },
    { station: "Geylang Bahru", abbr: "GLB" },
    { station: "Mattar", abbr: "MTR" },
    { station: "Ubi", abbr: "UBI" },
    { station: "Kaki Bukit", abbr: "KKB" },
    { station: "Bedok North", abbr: "BDN" },
    { station: "Bedok Reservoir", abbr: "BDR" },
    { station: "Tampines West", abbr: "TPW" },
    { station: "Tampines East", abbr: "TPE" },
    { station: "Upper Changi", abbr: "UPC" },
    { station: "Woodlands North", abbr: "WDN" },
    { station: "Woodlands South", abbr: "WDS" },
    { station: "Springleaf", abbr: "SPL" },
    { station: "Lentor", abbr: "LTR" },
    { station: "Mayflower", abbr: "MFL" },
    { station: "Bright Hill", abbr: "BRH" },
    { station: "Upper Thomson", abbr: "UTS" },
    { station: "Napier", abbr: "NPR" },
    { station: "Orchard Boulevard", abbr: "OBV" },
    { station: "Great World", abbr: "GRW" },
    { station: "Havelock", abbr: "HVL" },
    { station: "Maxwell", abbr: "MAX" },
    { station: "Shenton Way", abbr: "SHW" },
    { station: "Gardens by the Bay", abbr: "GRB" },
  ],
};
