export const questionBank = {
  questions: [
    { station: "Pasir Ris", abbr: "PSR" },
    { station: "Tampines", abbr: "TAM" },
    { station: "Simei", abbr: "SIM" },
    { station: "Tanah Merah", abbr: "TNM" },
    { station: "Bedok", abbr: "BDK" },
    { station: "Kembangan", abbr: "KEM" },
    { station: "Eunos", abbr: "EUN" },
    { station: "Paya Lebar", abbr: "PYL" },
    { station: "Aljunied", abbr: "ALJ" },
    { station: "Kallang", abbr: "KAL" },
    { station: "Lavender", abbr: "LVR" },
    { station: "Bugis", abbr: "BGS" },
    { station: "City Hall", abbr: "CTH" },
    { station: "Raffles Place", abbr: "RFP" },
    { station: "Tanjong Pagar", abbr: "TPG" },
    { station: "Outram Park", abbr: "OTP" },
    { station: "Tiong Bahru", abbr: "TIB" },
    { station: "Redhill", abbr: "RDH" },
    { station: "Queenstown", abbr: "QUE" },
    { station: "Commonwealth", abbr: "COM" },
    { station: "Buona Vista", abbr: "BNV" },
    { station: "Dover", abbr: "DVR" },
    { station: "Clementi", abbr: "CLE" },
    { station: "Jurong East", abbr: "JUR" },
    { station: "Chinese Garden", abbr: "CNG" },
    { station: "Lakeside", abbr: "LKS" },
    { station: "Boon Lay", abbr: "BNL" },
    { station: "Pioneer", abbr: "PNR" },
    { station: "Joo Koon", abbr: "JKN" },
    { station: "Gul Circle", abbr: "GCL" },
    { station: "Tuas Crescent", abbr: "TCR" },
    { station: "Tuas West Road", abbr: "TWR" },
    { station: "Tuas Link", abbr: "TLK" },
    { station: "Expo", abbr: "XPO" },
    { station: "Changi Airport", abbr: "CGA" },
  ],
};
